title: est.social
description: Juhendid ja abimaterjalid
theme: just-the-docs
url: https://infoaed.github.io

lang: et
locale: et_EE

aux_links:
  Materjalid GitHubis: https://github.com/est-social/est-social.github.io

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  news:
    permalink: "/:collection/:path/"
    output: true
  docs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    docs:
      name: Juhendid
      nav_exclude: false
      nav_fold: false
      search_exclude: false
    news:
      name: Uudised
      nav_exclude: false
      nav_fold: true
      search_exclude: false

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
